### ISSUE TITLE
[Suggestion] More configs

### ISSUE THREAD

**Issue by Playeroth** [Exiled-Team/Scp035#19]
More configs for Scp035, atm the old ReadMe is still there and if you look though the actual plugin config it was many lack of options, no corrode trails, damage when in range or the old system to infect random items
having most of it, (if not all of it)configs that are in readme to the most recent plugin config it would be way customizable.

**Comment by joker-119** [comment]
Yea the config in the readme is outdated and I haven't updated it yet, but the core aspects of the original plugin were scrapped when I re-wrote it. That's why the 'infected' item is a single (or multiple) specific items, not existing items chosen at random. I'm not sure how I could do corrode trails, but I'll look into adapting 106 sinkholes ore something.
As for the damage when in range, is that supposed to be damage when in range of the item, or of the player, because neither of those fit within the proper lore of SCP-035.

**Comment by Playeroth** [comment]
damage when in range should be like the 'corrode players' tab from readme, 'Scp035 modifiers' should be there too atleast, since you can choose many things like 'self_inflic'
and the problem with spawn infected item is that you can only set a predetermined item to spawn inside lockers, which is very predictable where it will spawn(and sometimes looks like doesnt spawns, works kinda weird when trying to spawn weapons) making you rush to find something that yourself will benefit from taking the infected item.

**Comment by joker-119** [comment]
There *are* other locations you can spawn it aside from Lockers. 
You can also have a plethora of different possible spawn locations and one is picked at random.
self_inflic will never be a config option. It will always infect the person who picks it up.
I also don't really see why corroding players by just being around them would be a thing. AFAIK in the SCP-035 lore, it's only the host that gets corroded.

**Comment by Playeroth** [comment]
i see, thanks for the response.
